### ISSUE TITLE
Address Duplication/Crash

### ISSUE THREAD

**Issue by gb-mobile** [pokecrystal-mobile/pokecrystal-mobile-en#53]
Identify and fix bug that causes the last address option to duplicate in the Mobile Profile > Address menu when scrolling down/up.
Selecting the duplicate causes the game to crash.

![image](https://github.com/gb-mobile/pokecrystal-mobile-eng/assets/110418063/ce25957c-0cf0-4dcd-9514-59ba73644adc)

**Comment by Lorenzooone** [comment]
NUM_REGION_CODES is 64, yet the list defined at https://github.com/gb-mobile/pokecrystal-mobile-eng/blob/913ac7baf734555a1efdd62503b6ce00fe460537/mobile/mobile_12.asm#L819 only contains 63 entries.
I'd suggest placing an assert to avoid these kinds of issues.
